spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${RABBIT_URL}
    port: 5672
    username: api-movements
    password: api-movements
logging:
  level:
    root: INFO
