spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expenses?createDatabaseIfNotExist=true
    username: root
    password: helios
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: api-movements
    password: api-movements

logging:
  level:
    root: INFO
