name: general.yml
name: CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]

env:
  IMAGE_NAME: "mferrerovilas/api-expenses"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Prepare Gradle
        run: |
          chmod +x gradlew
          ./gradlew --version

      - name: Compute Version
        id: version
        run: |
          BUILD_VERSION=$(./gradlew printVersion --quiet)

          if [[ "${GITHUB_REF_NAME}" == "develop" ]] || [[ "${GITHUB_REF_NAME}" == hotfix/* ]]; then
            PHASE="-SNAPSHOT"
          else
            PHASE=""
          fi

          echo "version=${BUILD_VERSION}${PHASE}" >> $GITHUB_OUTPUT

          echo "${BUILD_VERSION}${PHASE}" > build.version
          echo "${PHASE}" > build.phase

      - name: Build JAR
        run: ./gradlew clean assemble --stacktrace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build.version
            build.phase
            build/libs/*.jar
            build/resources/*.jar

  approve:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Require Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: "mferrero"   # Cambiar si quer√©s usar otro usuario
          minimum-approvals: 1

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

  deploy:
    needs: [ build, approve ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          VERSION=$(cat build.version)
          
          docker build \
            --platform linux/arm64 \
            -t $IMAGE_NAME:$VERSION \
            -t $IMAGE_NAME:latest .

          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
 
